CREATE TABLE COUNTIES (
    ID_COUNTY INT NOT NULL,
    COUNTY_NAME VARCHAR(255) NOT NULL,
    COUNTY_CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_COUNTY)
) AS SELECT * FROM CSVREAD('classpath:/county.csv');

CREATE TABLE LOCALITIES (
    ID INT NOT NULL,
    LOCALITY_NAME VARCHAR(255) NOT NULL,
    COUNTY_CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (COUNTY_CODE) REFERENCES COUNTIES(COUNTY_CODE)
) AS SELECT * FROM CSVREAD('classpath:/locality.csv');

CREATE TABLE USERS_DATA (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
)
